general {
	lock_cmd = pidof hyprlock || hyprlock		# Avoid starting multiple hyprlock instances
	before_sleep_cmd = hyprlock 			# Lock before suspend
	after_sleep_cmd = hyprctl dispatch dpms on 	# To avoid having to press a key to turn on the display
}

# Screen light dimming after 2:30 minutes
listener {
	timeout = 900
	on-timeout = brightnessctl -s set 10		# Set brightness to 10%
	on-resume = brightnessctl -r 			# Set brightness back up
}

# Turn off keyboard lighting after 2:30 minutes
listener {
	timeout = 900
	on-timeout = brightnessctl -d asus::kbd_backlight set 0 	# Turn off keyboard lighting
	on-resume = brightnessctl -d asus::kbd_backlight set 2		# Turn on keyboard lighting at 66%
}

# Suspend after 5 minutes
listener {
	timeout = 1800 
	on-timeout = systemctl suspend			# Suspend session
}
